export const MODAL_OPEN = "MODAL_OPEN";

export const VAULT_SELECTED = "VAULT_SELECTED";

export const VAULT_FETCH_REQUESTED = "VAULT_FETCH_REQUESTED";
export const VAULT_FETCH_SUCCEEDED = "VAULT_FETCH_SUCCEEDED";
export const VAULT_FETCH_FAILED = "VAULT_FETCH_FAILED";

export const VAULT_ADD_REQUESTED = "VAULT_ADD_REQUESTED";
export const VAULT_ADD_SUCCEEDED = "VAULT_ADD_SUCCEEDED";
export const VAULT_ADD_FAILED = "VAULT_ADD_FAILED";

export const VAULT_UPDATE_REQUESTED = "VAULT_UPDATE_REQUESTED";
export const VAULT_UPDATE_SUCCEEDED = "VAULT_UPDATE_SUCCEEDED";
export const VAULT_UPDATE_FAILED = "VAULT_UPDATE_FAILED";

export const VAULT_DELETE_REQUESTED = "VAULT_DELETE_REQUESTED";
export const VAULT_DELETE_SUCCEEDED = "VAULT_DELETE_SUCCEEDED";
export const VAULT_DELETE_FAILED = "VAULT_DELETE_FAILED";
